#!/usr/bin/env bash

help='
Usage:
    importi3config <i3-config-file>...
    importi3config --help
'

# Show help
if [ $# -eq 0 -o "$1" = '--help' ]
then
    echo "$help"
    exit 0
fi

for arg in "$@"
do
    [ -f $arg ] || {
        echo "$arg: No such config file." 1>&2
        exit 1
    }

    # Ignore comment
    i3command=$(grep -v "#.*" $arg)

    # Accept setting
    i3-msg "$i3command"
done
